In [78]:
import pandas as pd

In [79]:
df = pd.read_csv('emails.csv')

In [80]:
df.shape

(5728, 2)

In [81]:
df = df.drop_duplicates()

In [82]:
df.shape

(5695, 2)

In [83]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5695 entries, 0 to 5727
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   text    5695 non-null   object
 1   spam    5695 non-null   int64 
dtypes: int64(1), object(1)
memory usage: 133.5+ KB


In [84]:
df.head()

,text,spam
0,Subject: naturally irresistible your corporate...,1
1,Subject: the stock trading gunslinger fanny i...,1
2,Subject: unbelievable new homes made easy im ...,1
3,Subject: 4 color printing special request add...,1
4,"Subject: do not have money , get software cds ...",1


In [85]:
df['spam'].value_counts()

spam
0    4327
1    1368
Name: count, dtype: int64

In [86]:
df.isnull().sum()

text    0
spam    0
dtype: int64

In [87]:
X = df['text']
y = df['spam']

In [88]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

In [89]:
X_train.shape

(3986,)

In [90]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    lowercase=True,
    stop_words='english'
)

In [91]:
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

In [92]:
print(X_train_tfidf.shape)
print(X_test_tfidf.shape)

(3986, 31300)
(1709, 31300)


In [93]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, recall_score, f1_score, confusion_matrix, classification_report

lr = LogisticRegression()
lr.fit(X_train_tfidf, y_train)
y_pred = lr.predict(X_test_tfidf)
y_pred_train = lr.predict(X_train_tfidf)

print('train')
print(accuracy_score(y_train, y_pred_train))
print(recall_score(y_train, y_pred_train))
print(f1_score(y_train, y_pred_train))
print(confusion_matrix(y_train, y_pred_train))
print(classification_report(y_train, y_pred_train))

print('test')
print(accuracy_score(y_test, y_pred))
print(recall_score(y_test, y_pred))
print(f1_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

train
0.9934771700953337
0.9749216300940439
0.9862579281183932
[[3027    2]
 [  24  933]]
              precision    recall  f1-score   support

           0       0.99      1.00      1.00      3029
           1       1.00      0.97      0.99       957

    accuracy                           0.99      3986
   macro avg       0.99      0.99      0.99      3986
weighted avg       0.99      0.99      0.99      3986

test
0.9806904622586308
0.927007299270073
0.9584905660377359
[[1295    3]
 [  30  381]]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99      1298
           1       0.99      0.93      0.96       411

    accuracy                           0.98      1709
   macro avg       0.98      0.96      0.97      1709
weighted avg       0.98      0.98      0.98      1709



In [95]:
from sklearn.naive_bayes import  GaussianNB

naive = GaussianNB()
naive.fit(X_train_tfidf.toarray(), y_train)
y_pred = naive.predict(X_test_tfidf.toarray())
y_pred_train = naive.predict(X_train_tfidf.toarray())

print('train')
print(accuracy_score(y_train, y_pred_train))
print(recall_score(y_train, y_pred_train))
print(f1_score(y_train, y_pred_train))
print(confusion_matrix(y_train, y_pred_train))
print(classification_report(y_train, y_pred_train))

print('test')
print(accuracy_score(y_test, y_pred))
print(recall_score(y_test, y_pred))
print(f1_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

train
0.9977420973406924
1.0
0.9953198127925117
[[3020    9]
 [   0  957]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3029
           1       0.99      1.00      1.00       957

    accuracy                           1.00      3986
   macro avg       1.00      1.00      1.00      3986
weighted avg       1.00      1.00      1.00      3986

test
0.9531889994148625
0.8491484184914841
0.897172236503856
[[1280   18]
 [  62  349]]
              precision    recall  f1-score   support

           0       0.95      0.99      0.97      1298
           1       0.95      0.85      0.90       411

    accuracy                           0.95      1709
   macro avg       0.95      0.92      0.93      1709
weighted avg       0.95      0.95      0.95      1709



In [98]:
from sklearn.naive_bayes import  GaussianNB

naive = GaussianNB()
naive.fit(X_train_tfidf, y_train)
y_pred = naive.predict(X_test_tfidf)
y_pred_train = naive.predict(X_train_tfidf)

print('train')
print(accuracy_score(y_train, y_pred_train))
print(recall_score(y_train, y_pred_train))
print(f1_score(y_train, y_pred_train))
print(confusion_matrix(y_train, y_pred_train))
print(classification_report(y_train, y_pred_train))

print('test')
print(accuracy_score(y_test, y_pred))
print(recall_score(y_test, y_pred))
print(f1_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

TypeError: Sparse data was passed for X, but dense data is required. Use '.toarray()' to convert to a dense numpy array.

In [96]:
from sklearn.neighbors import  KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=4)
knn.fit(X_train_tfidf.toarray(), y_train)
y_pred = knn.predict(X_test_tfidf.toarray())
y_pred_train = knn.predict(X_train_tfidf.toarray())

print('train')
print(accuracy_score(y_train, y_pred_train))
print(recall_score(y_train, y_pred_train))
print(f1_score(y_train, y_pred_train))
print(confusion_matrix(y_train, y_pred_train))
print(classification_report(y_train, y_pred_train))

print('test')
print(accuracy_score(y_test, y_pred))
print(recall_score(y_test, y_pred))
print(f1_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

train
0.9811841445057702
0.9247648902821317
0.959349593495935
[[3026    3]
 [  72  885]]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99      3029
           1       1.00      0.92      0.96       957

    accuracy                           0.98      3986
   macro avg       0.99      0.96      0.97      3986
weighted avg       0.98      0.98      0.98      3986

test
0.9748390871854886
0.9075425790754258
0.9455006337135615
[[1293    5]
 [  38  373]]
              precision    recall  f1-score   support

           0       0.97      1.00      0.98      1298
           1       0.99      0.91      0.95       411

    accuracy                           0.97      1709
   macro avg       0.98      0.95      0.96      1709
weighted avg       0.98      0.97      0.97      1709

